import React, { useEffect, useState } from 'react';
import { History, ShieldAlert, Download, Trash2, FileText } from 'lucide-react';
import { ScanResult } from '../types';
import { DEMO_PRESETS } from '../services/demoData';

export const SecurityHistory: React.FC = () => {
  const [historyList, setHistoryList] = useState<ScanResult[]>([]);

  useEffect(() => {
    // Populate initial history from demo presets
    setHistoryList(DEMO_PRESETS.map(p => p.result));
  }, []);

  const handleDownloadReport = (result: ScanResult) => {
    const reportText = `CYBER SHIELD X INCIDENT SECURITY REPORT
--------------------------------------------------
Scan ID: CSX-${Math.floor(100000 + Math.random() * 900000)}
Input Type: ${result.scan_type.toUpperCase()}
Target Input: ${result.target_input}
Risk Score: ${result.risk_score} / 100 (${result.threat_level})
Confidence: ${result.confidence}%

KEY EVIDENCE & REASONS:
${result.reasons.map(r => `- ${r}`).join('\n')}

RECOMMENDED ACTIONS:
${result.recommendations.map(r => `- ${r}`).join('\n')}

AI EXPLANATION:
${result.ai_explanation || 'N/A'}
--------------------------------------------------
Generated by CYBER SHIELD X - Check Before You Trust
`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `CyberShieldX_Report_${result.scan_type}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto py-4 px-4">
      <div className="flex items-center justify-between pb-4 border-b border-slate-800">
        <div className="flex items-center gap-3">
          <div className="p-3 bg-slate-800 border border-slate-700 rounded-xl text-slate-300">
            <History className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-white">Security History & Incident Log</h1>
            <p className="text-xs text-slate-400">View recent threat evaluations and download structured incident reports.</p>
          </div>
        </div>

        <button
          onClick={() => setHistoryList([])}
          className="px-3 py-1.5 bg-slate-900 hover:bg-red-950/40 text-slate-400 hover:text-red-300 border border-slate-800 rounded-lg text-xs flex items-center gap-1.5 transition-colors"
        >
          <Trash2 className="w-3.5 h-3.5" /> Clear History
        </button>
      </div>

      <div className="space-y-3">
        {historyList.length === 0 ? (
          <div className="glass-panel p-10 text-center text-slate-500 text-xs">
            No history logs found. Scan a URL, QR code, or message to populate logs.
          </div>
        ) : (
          historyList.map((item, idx) => (
            <div key={idx} className="glass-panel p-4 flex flex-wrap items-center justify-between gap-4 border-slate-800 hover:border-slate-700 transition-colors">
              <div className="flex items-center gap-3">
                <span className={`px-2.5 py-1 rounded-lg text-[10px] font-black uppercase font-mono border ${
                  item.threat_level === 'CRITICAL' || item.threat_level === 'HIGH'
                    ? 'bg-red-500/20 text-red-400 border-red-500/40'
                    : item.threat_level === 'MEDIUM'
                    ? 'bg-amber-500/20 text-amber-400 border-amber-500/40'
                    : 'bg-emerald-500/20 text-emerald-400 border-emerald-500/40'
                }`}>
                  {item.threat_level} ({item.risk_score}/100)
                </span>
                <div>
                  <div className="text-xs font-bold text-slate-200 line-clamp-1 break-all">
                    [{item.scan_type.toUpperCase()}] {item.target_input}
                  </div>
                  <div className="text-[11px] text-slate-400">
                    {item.reasons[0] || 'Standard scan checks passed.'}
                  </div>
                </div>
              </div>

              <button
                onClick={() => handleDownloadReport(item)}
                className="px-3 py-1.5 bg-sky-500/10 hover:bg-sky-500/20 text-sky-300 border border-sky-500/30 rounded-lg text-xs font-semibold flex items-center gap-1.5 transition-all"
              >
                <Download className="w-3.5 h-3.5" /> Report TXT
              </button>
            </div>
          ))
        )}
      </div>
    </div>
  );
};
